spring:
  application:
    name: simpleboard
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/used_trading_site?serverTimezone=UTC&characterEncoding=UTF-8
    username: seongmin
    password: 1234

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
